"""knowledge access control and tabular knowledge (Noblen AI 3.0, M3)

Adds knowledge_access_grants, knowledge_tables, knowledge_table_rows and the
visibility columns (existing rows default to ORGANIZATION / INHERIT, i.e. no
change in who can read them). Hand-edited: pre-existing autogenerate drift
(agents active-version FK, document_embeddings FK, the pgvector HNSW index) is
intentionally NOT touched.

Revision ID: 3a27a8c10dcf
Revises: 179df45d96e3
Create Date: 2026-09-27 17:09:14.688125
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a27a8c10dcf'
down_revision: str | None = '179df45d96e3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_access_grants',
    sa.Column('resource_type', sa.String(length=24), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('principal_type', sa.String(length=8), nullable=False),
    sa.Column('principal', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_type', 'resource_id', 'principal_type', 'principal', name='uq_knowledge_grant')
    )
    op.create_index(op.f('ix_knowledge_access_grants_organization_id'), 'knowledge_access_grants', ['organization_id'], unique=False)
    op.create_index(op.f('ix_knowledge_access_grants_principal'), 'knowledge_access_grants', ['principal'], unique=False)
    op.create_index(op.f('ix_knowledge_access_grants_resource_id'), 'knowledge_access_grants', ['resource_id'], unique=False)
    op.create_table('knowledge_tables',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'name', name='uq_table_document_name')
    )
    op.create_index(op.f('ix_knowledge_tables_document_id'), 'knowledge_tables', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_tables_knowledge_base_id'), 'knowledge_tables', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_knowledge_tables_organization_id'), 'knowledge_tables', ['organization_id'], unique=False)
    op.create_table('knowledge_table_rows',
    sa.Column('table_id', sa.Uuid(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['knowledge_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'row_index', name='uq_table_row_index')
    )
    op.create_index(op.f('ix_knowledge_table_rows_organization_id'), 'knowledge_table_rows', ['organization_id'], unique=False)
    op.create_index(op.f('ix_knowledge_table_rows_table_id'), 'knowledge_table_rows', ['table_id'], unique=False)
    op.add_column('knowledge_bases', sa.Column('visibility', sa.String(length=16), server_default='ORGANIZATION', nullable=False))
    op.add_column('knowledge_documents', sa.Column('visibility', sa.String(length=16), server_default='INHERIT', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_documents', 'visibility')
    op.drop_column('knowledge_bases', 'visibility')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_index(op.f('ix_knowledge_table_rows_table_id'), table_name='knowledge_table_rows')
    op.drop_index(op.f('ix_knowledge_table_rows_organization_id'), table_name='knowledge_table_rows')
    op.drop_table('knowledge_table_rows')
    op.drop_index(op.f('ix_knowledge_tables_organization_id'), table_name='knowledge_tables')
    op.drop_index(op.f('ix_knowledge_tables_knowledge_base_id'), table_name='knowledge_tables')
    op.drop_index(op.f('ix_knowledge_tables_document_id'), table_name='knowledge_tables')
    op.drop_table('knowledge_tables')
    op.drop_index(op.f('ix_knowledge_access_grants_resource_id'), table_name='knowledge_access_grants')
    op.drop_index(op.f('ix_knowledge_access_grants_principal'), table_name='knowledge_access_grants')
    op.drop_index(op.f('ix_knowledge_access_grants_organization_id'), table_name='knowledge_access_grants')
    op.drop_table('knowledge_access_grants')
    # ### end Alembic commands ###
