"""long-term memory (Noblen AI 3.0, M4)

Adds the scoped `memories` table (USER / AGENT / ORGANIZATION) and the
organizations.memory_retention_days setting (null = keep until deleted).
Hand-edited: pre-existing autogenerate drift (agents active-version FK,
document_embeddings FK, the pgvector HNSW index) is intentionally NOT touched.

Revision ID: 121c8c4186bf
Revises: 3a27a8c10dcf
Create Date: 2026-09-27 17:25:02.144475
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '121c8c4186bf'
down_revision: str | None = '3a27a8c10dcf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_by_agent_id', sa.Uuid(), nullable=True),
    sa.Column('source_run_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_agent_id'), 'memories', ['agent_id'], unique=False)
    op.create_index('ix_memories_org_scope', 'memories', ['organization_id', 'scope'], unique=False)
    op.create_index(op.f('ix_memories_organization_id'), 'memories', ['organization_id'], unique=False)
    op.create_index(op.f('ix_memories_user_id'), 'memories', ['user_id'], unique=False)
    op.add_column('organizations', sa.Column('memory_retention_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'memory_retention_days')
    op.drop_index(op.f('ix_memories_user_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_organization_id'), table_name='memories')
    op.drop_index('ix_memories_org_scope', table_name='memories')
    op.drop_index(op.f('ix_memories_agent_id'), table_name='memories')
    op.drop_table('memories')
    # ### end Alembic commands ###
