"""add agent engine (phase 3)

Revision ID: 4d838a423ef5
Revises: c9b08e38cf92
Create Date: 2026-09-19 23:21:19.084209
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d838a423ef5'
down_revision: str | None = 'c9b08e38cf92'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tools',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('output_schema', sa.JSON(), nullable=False),
    sa.Column('tool_type', sa.String(length=32), nullable=False),
    sa.Column('permission_mode', sa.String(length=24), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('handler_identifier', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tools_name'), ['name'], unique=True)

    op.create_table('agents',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('agent_type', sa.String(length=32), nullable=False),
    sa.Column('default_provider', sa.String(length=64), nullable=True),
    sa.Column('default_model', sa.String(length=128), nullable=True),
    sa.Column('system_instructions', sa.Text(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('memory_mode', sa.String(length=16), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('agent_metadata', sa.JSON(), nullable=False),
    sa.Column('active_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['active_version_id'], ['agent_versions.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_agent_org_slug')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_agent_type'), ['agent_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_status'), ['status'], unique=False)

    op.create_table('agent_tools',
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('tool_id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('permission_mode', sa.String(length=24), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'tool_id', name='uq_agent_tool')
    )
    with op.batch_alter_table('agent_tools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_tools_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_tools_tool_id'), ['tool_id'], unique=False)

    op.create_table('agent_versions',
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('system_instructions', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('memory_configuration', sa.JSON(), nullable=False),
    sa.Column('tool_configuration', sa.JSON(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'version_number', name='uq_agent_version_number')
    )
    with op.batch_alter_table('agent_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_versions_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_versions_organization_id'), ['organization_id'], unique=False)

    op.create_table('conversations',
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('conversation_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_status'), ['status'], unique=False)

    op.create_table('approvals',
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('tool_call_id', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by', sa.Uuid(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_status'), ['status'], unique=False)

    op.create_table('conversation_messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_metadata', sa.JSON(), nullable=False),
    sa.Column('agent_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_messages_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_messages_sequence'), ['sequence'], unique=False)

    op.create_table('conversation_participants',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uq_conversation_participant')
    )
    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_participants_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_participants_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_participants_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('ai_usage_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_version_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('conversation_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ai_usage_records_agent_version_id'), ['agent_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_records_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_usage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_records_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_records_agent_version_id'))
        batch_op.drop_column('conversation_id')
        batch_op.drop_column('agent_version_id')

    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_participants_organization_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_participants_conversation_id'))

    op.drop_table('conversation_participants')
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_messages_sequence'))
        batch_op.drop_index(batch_op.f('ix_conversation_messages_organization_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_messages_conversation_id'))

    op.drop_table('conversation_messages')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_status'))
        batch_op.drop_index(batch_op.f('ix_approvals_organization_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_agent_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_status'))
        batch_op.drop_index(batch_op.f('ix_conversations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_agent_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('agent_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_versions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_agent_versions_agent_id'))

    op.drop_table('agent_versions')
    with op.batch_alter_table('agent_tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_tools_tool_id'))
        batch_op.drop_index(batch_op.f('ix_agent_tools_agent_id'))

    op.drop_table('agent_tools')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_status'))
        batch_op.drop_index(batch_op.f('ix_agents_slug'))
        batch_op.drop_index(batch_op.f('ix_agents_organization_id'))
        batch_op.drop_index(batch_op.f('ix_agents_agent_type'))

    op.drop_table('agents')
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tools_name'))

    op.drop_table('tools')
    # ### end Alembic commands ###
