"""integrations (Noblen AI 3.0, M6)

Adds integration_connections (credentials encrypted at rest), integration_tools
(imported MCP tools), tools.organization_id (organization-owned tools) and
workflows.webhook_token_hash (webhook triggers). Hand-edited: the tools FK is
named, and pre-existing autogenerate drift (agents active-version FK,
document_embeddings FK, the pgvector HNSW index) is intentionally NOT touched.

Revision ID: 08100b04d46f
Revises: ec44db57f95a
Create Date: 2026-09-27 20:49:28.581594
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08100b04d46f'
down_revision: str | None = 'ec44db57f95a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_connections',
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('secret_ciphertext', sa.Text(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_integration_connection_name')
    )
    op.create_index(op.f('ix_integration_connections_organization_id'), 'integration_connections', ['organization_id'], unique=False)
    op.create_index(op.f('ix_integration_connections_provider'), 'integration_connections', ['provider'], unique=False)
    op.create_table('integration_tools',
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('tool_id', sa.Uuid(), nullable=False),
    sa.Column('remote_name', sa.String(length=128), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'remote_name', name='uq_integration_tool_remote'),
    sa.UniqueConstraint('tool_id')
    )
    op.create_index(op.f('ix_integration_tools_organization_id'), 'integration_tools', ['organization_id'], unique=False)
    op.add_column('tools', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_tools_organization_id'), 'tools', ['organization_id'], unique=False)
    op.create_foreign_key('fk_tools_organization_id', 'tools', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('workflows', sa.Column('webhook_token_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'webhook_token_hash')
    op.drop_constraint('fk_tools_organization_id', 'tools', type_='foreignkey')
    op.drop_index(op.f('ix_tools_organization_id'), table_name='tools')
    op.drop_column('tools', 'organization_id')
    op.drop_index(op.f('ix_integration_tools_organization_id'), table_name='integration_tools')
    op.drop_table('integration_tools')
    op.drop_index(op.f('ix_integration_connections_provider'), table_name='integration_connections')
    op.drop_index(op.f('ix_integration_connections_organization_id'), table_name='integration_connections')
    op.drop_table('integration_connections')
    # ### end Alembic commands ###
