"""add ai usage records

Revision ID: c9b08e38cf92
Revises: a4ca89bed940
Create Date: 2026-09-19 20:30:10.368768
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9b08e38cf92'
down_revision: str | None = 'a4ca89bed940'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage_records',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('workflow_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('estimated_cost_currency', sa.String(length=8), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_type', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_records_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_records_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_records_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_records_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_records_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_records_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_records_workflow_id'), ['workflow_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_usage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_records_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_records_request_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_records_provider'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_records_organization_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_records_model'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_records_agent_id'))

    op.drop_table('ai_usage_records')
    # ### end Alembic commands ###
